---
abstract: 'Use the revision of the working directory'
author:
  - 'Olivier Mengué <dolmen@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::Kwalitee: 0
  Test::More: 0
  Test::Pod: 1.00
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Version-FromSubversion
requires:
  Alien::SVN: 0
  Moose: 0
  SVN::Client: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-Plugin-Version-FromSubversion
version: 1.000002
